// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/8/2024, 5:14:48 PM
const configMerger = require("D:/P-Ninja/nuxt-waterflow/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/P-Ninja/nuxt-waterflow/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/P-Ninja/nuxt-waterflow/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/P-Ninja/nuxt-waterflow/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/P-Ninja/nuxt-waterflow/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/P-Ninja/nuxt-waterflow/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/P-Ninja/nuxt-waterflow/plugins/**/*.{js,ts,mjs}","D:/P-Ninja/nuxt-waterflow/composables/**/*.{js,ts,mjs}","D:/P-Ninja/nuxt-waterflow/utils/**/*.{js,ts,mjs}","D:/P-Ninja/nuxt-waterflow/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/P-Ninja/nuxt-waterflow/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/P-Ninja/nuxt-waterflow/app.config.{js,ts,mjs}"] }));

module.exports = config
